POST http://localhost:3000/login
Content-Type: application/json

{
    "userId" : "aarohi@gmail.com",
    "password": "Welcome@123"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "userId" : "aarohi@gmail.com",
    "password": "Welcome@123"
}

###
POST http://localhost:3000/user/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYXJvaGlAZ21haWwuY29tIiwiaWF0IjoxNjQ4NDg2ODQxLCJleHAiOjE2NDg0ODczNDF9.MmpdUHBtcIrquXtHUVFOJYEOHwhq3AsPazb_JnLRnsg

{
    "userId" : "aarohi@gmail.com",
    "post": "This is my First Post"
}

###
GET http://localhost:3000/user/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYXJvaGlAZ21haWwuY29tIiwiaWF0IjoxNjQ4NDg2ODQxLCJleHAiOjE2NDg0ODczNDF9.MmpdUHBtcIrquXtHUVFOJYEOHwhq3AsPazb_JnLRnsg 

{
    "userId" : "aarohi@gmail.com"
}
###

POST http://localhost:3000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJyYWh1bC5taHQyNTA5M0BnbWFpbC5jb20iLCJpYXQiOjE2NDcxNzc1Mjh9.BSA0HGiT_55bfNnq_NZAVFsP4mp2OCfcSojRl8ouM80"
}

###